//
// Created by adity on 13-09-2026.
//

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename	"PsyBass.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"PsyBass VST3 (64Bit)"
#else
#define stringFileDescription	"PsyBass VST3"
#endif
#define stringCompanyName		"X-Design Team\0"
#define stringLegalCopyright	"Copyright(c) 2026 X-Design Team"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
